<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2322" started-at="2021-12-05T06:38:36Z" finished-at="2021-12-05T06:38:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2322" started-at="2021-12-05T06:38:36Z" finished-at="2021-12-05T06:38:38Z">
      <class name="com.jbk.test.LoginTest">
        <test-method status="PASS" signature="browserSetup()[pri:0, instance:com.jbk.test.LoginTest@520a3426]" name="browserSetup" is-config="true" duration-ms="6365" started-at="2021-12-04T22:38:30Z" finished-at="2021-12-04T22:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetup -->
        <test-method status="PASS" signature="verifyline()[pri:1, instance:com.jbk.test.LoginTest@520a3426]" name="verifyline" duration-ms="146" started-at="2021-12-04T22:38:36Z" finished-at="2021-12-04T22:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyline -->
        <test-method status="PASS" signature="verifyregistertext()[pri:2, instance:com.jbk.test.LoginTest@520a3426]" name="verifyregistertext" duration-ms="72" started-at="2021-12-04T22:38:36Z" finished-at="2021-12-04T22:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyregistertext -->
        <test-method status="PASS" signature="verifyloginpass()[pri:3, instance:com.jbk.test.LoginTest@520a3426]" name="verifyloginpass" duration-ms="932" started-at="2021-12-04T22:38:36Z" finished-at="2021-12-04T22:38:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginpass -->
        <test-method status="PASS" signature="verifyerrorlogin()[pri:4, instance:com.jbk.test.LoginTest@520a3426]" name="verifyerrorlogin" duration-ms="464" started-at="2021-12-04T22:38:37Z" finished-at="2021-12-04T22:38:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyerrorlogin -->
        <test-method status="FAIL" signature="verifyBlankData()[pri:5, instance:com.jbk.test.LoginTest@520a3426]" name="verifyBlankData" duration-ms="329" started-at="2021-12-04T22:38:38Z" finished-at="2021-12-04T22:38:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.jbk.test.LoginTest.verifyBlankData(LoginTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBlankData -->
        <test-method status="FAIL" signature="verifycorrectloginpass()[pri:6, instance:com.jbk.test.LoginTest@520a3426]" name="verifycorrectloginpass" duration-ms="326" started-at="2021-12-04T22:38:38Z" finished-at="2021-12-04T22:38:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.jbk.test.LoginTest.verifycorrectloginpass(LoginTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycorrectloginpass -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.jbk.test.LoginTest@520a3426]" name="teardown" is-config="true" duration-ms="0" started-at="2021-12-04T22:38:38Z" finished-at="2021-12-04T22:38:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.jbk.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
